config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'

  get '/profile' => 'pages#profile'

  resources :projects do
    member do
      post :back
    end
  end

  resources :wallets, only: [:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :projects
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :project
  has_many :transactions


  def confirmDone(admin_password)
    contract = find_contract_by_address
    contract.key = EthereumWallet.admin_key(admin_password)
    transaction = contract.transact_and_wait.confirm_done()
  end

  def cancelFundings(admin_password)
    contract = find_contract_by_address
    contract.key = EthereumWallet.admin_key(admin_password)
    transaction = contract.transact_and_wait.cancel_fundings()
  end

  def donate(user, password, payment_amount)
    contract = find_contract_by_address
    contract.key = user.ethereum_wallet.decrypted_key(password)
    contract.custom_value = payment_amount.to_i
    transaction = contract.transact_and_wait.donate(user.id)

    Transaction.create(user_id: user.id, value: payment_amount, project_id: project_id, address: transaction.id)
  end

  def balance
    Ethereum::IpcClient.new.get_balance address
  end

  private

  def find_contract_by_address
    Ethereum::Contract.create(file: Rails.root.join('app','contracts','kickstarter.sol'), address: address)
  end
end

app/models/ethereum_wallet.rb
class EthereumWallet < Wallet
  before_validation :generate_wallet
  validates :user_id, :address, :key, presence: true

  def balance
    Ethereum::IpcClient.new.get_balance address
  end

  def decrypted_key(password)
    Eth::Key.decrypt self.key, password
  end


  def self.admin_key(password)
    Eth::Key.decrypt Rails.application.secrets.ether_wallet_key, password
  end

  attr_accessor :password

  def generate_wallet
    if check_password_complexity(password) && new_record?
      eth_key = Eth::Key.new
      self.address = eth_key.address # EIP55 checksummed address
      self.key = Eth::Key.encrypt eth_key, password
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_one :contract
  has_many :transactions

  validates :name, :description, :goal, :due_date, :user_id, presence: true
  validate :user_balance

  attr_accessor :password

  def pledged
    contract.balance rescue 0
  end

  def backers_count
    transactions.count
  end

  def deploy_contract(password)
    contract = Ethereum::Contract.create(file: Rails.root.join('app','contracts','kickstarter.sol'))
    contract.key = user.ethereum_wallet.decrypted_key(password)
    address = contract.deploy_and_wait(goal)
    Contract.create(project_id: id, address: address)
    
    FinishFundingJob.set(wait_until: due_date.end_of_day).perform_later(id)
  end

  def self.day_color(date)
    case date.to_date.wday
    when 0
      'bg-olive'
    when 1
      'bg-orange'
    when 2
      'bg-purple'
    when 3
      'bg-maroon'
    when 4
      'bg-blue'
    when 5
      'bg-navy'
    else
      'bg-red'
    end 
  end

  def user_balance
    errors.add(:base, 'Insufficient funds to deploy contract.') unless user.ethereum_wallet.try(:balance).to_i >= 10000000000000000
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :project
  
  attr_accessor :password
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
  has_many :transactions
  has_one :ethereum_wallet

end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user

  def balance
  end

  private

  def check_password_complexity(password)
    errors.add(:password, :upper_case) unless /[A-Z]/.match(password)
    errors.add(:password, :lower_case) unless /[a-z]/.match(password)
    errors.add(:password, :numbers) unless /\d/.match(password)
    errors.add(:password, :length) unless password.length >= 8
    !errors.any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :current_password, :name])
  end

  private

  def check_auth
    redirect_to new_user_session_path unless current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :check_auth, only: [:profile]

  def index
    @projects_by_date = Project.where(status: 'active').order('created_at DESC').group_by{|x| x.created_at.strftime("%d %b. %Y")}
  end

  def profile
    @transactions_by_date = Transaction.where(user_id: current_user.id).order('created_at DESC').group_by{|x| x.created_at.strftime("%d %b. %Y")}
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :check_auth, only: [:back, :create, :new]
  before_filter :find_project, only: [:show, :back, :edit]

  def index
    if params[:category] && (@category = Category.where(id: params[:category]).first)
      @projects_by_date = Project.where(status: 'active', category_id: params[:category]).order('created_at DESC').group_by{|x| x.created_at.strftime("%d %b. %Y")}
    else
      redirect_to root_path
    end
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      redirect_to project_path(@project)
    else
      flash[:alert] = @project.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
  end

  def back
    begin
      @project.contract.donate(current_user, params[:transaction][:password], params[:transaction][:value])
      redirect_to :back, notice: "Thank you for supporting #{@project.name}!";
    rescue Exception => e
      if e.message == 'Message Authentications Codes do not match!'
        redirect_to :back, alert: 'Wallet password is wrong';
      else
        redirect_to :back, alert: e.message
      end
    end
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :due_date, :goal, :category_id)
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_filter :check_auth

  def create
    if current_user.ethereum_wallet
      @message = 'You alredy have wallet'
      @close = true
    else
      wallet = EthereumWallet.create(user_id: current_user.id, password: params[:ethereum_wallet][:password])
      if wallet.id
        flash[:notice] = 'Ethereum Wallet created'
        @redirect = true
      else
        @message = wallet.errors[:password].join(', ')
        @close = false
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def wei_to_eth(value)
    number_with_precision(value.to_f/1_000_000_000_000_000_000, precision: 6, significant: true, strip_insignificant_zeros: true)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Coinstarter
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.hold-transition.skin-blue-light.layout-top-nav
    .wrapper
      = render partial: 'layouts/partials/header'
      / = render partial: 'layouts/partials/sidebar'
      .content-wrapper
        = yield
      = render partial: 'layouts/partials/footer'
      //= render partial: 'layouts/partials/control_sidebar
      = render partial: 'layouts/partials/modals'

app/views/layouts/partials/_control_sidebar.haml
/ Control Sidebar
%aside.control-sidebar.control-sidebar-dark
  / Create the tabs
  %ul.nav.nav-tabs.nav-justified.control-sidebar-tabs
    %li
      %a{"data-toggle" => "tab", :href => "#control-sidebar-home-tab"}
        %i.fa.fa-home
    %li
      %a{"data-toggle" => "tab", :href => "#control-sidebar-settings-tab"}
        %i.fa.fa-gears
  / Tab panes
  .tab-content
    / Home tab content
    #control-sidebar-home-tab.tab-pane
      %h3.control-sidebar-heading Recent Activity
      %ul.control-sidebar-menu
        %li
          %a{:href => "javascript:void(0)"}
            %i.menu-icon.fa.fa-birthday-cake.bg-red
            .menu-info
              %h4.control-sidebar-subheading Langdon's Birthday
              %p Will be 23 on April 24th
        %li
          %a{:href => "javascript:void(0)"}
            %i.menu-icon.fa.fa-user.bg-yellow
            .menu-info
              %h4.control-sidebar-subheading Frodo Updated His Profile
              %p New phone +1(800)555-1234
        %li
          %a{:href => "javascript:void(0)"}
            %i.menu-icon.fa.fa-envelope-o.bg-light-blue
            .menu-info
              %h4.control-sidebar-subheading Nora Joined Mailing List
              %p nora@example.com
        %li
          %a{:href => "javascript:void(0)"}
            %i.menu-icon.fa.fa-file-code-o.bg-green
            .menu-info
              %h4.control-sidebar-subheading Cron Job 254 Executed
              %p Execution time 5 seconds
      / /.control-sidebar-menu
      %h3.control-sidebar-heading Tasks Progress
      %ul.control-sidebar-menu
        %li
          %a{:href => "javascript:void(0)"}
            %h4.control-sidebar-subheading
              Custom Template Design
              %span.label.label-danger.pull-right 70%
            .progress.progress-xxs
              .progress-bar.progress-bar-danger{:style => "width: 70%"}
        %li
          %a{:href => "javascript:void(0)"}
            %h4.control-sidebar-subheading
              Update Resume
              %span.label.label-success.pull-right 95%
            .progress.progress-xxs
              .progress-bar.progress-bar-success{:style => "width: 95%"}
        %li
          %a{:href => "javascript:void(0)"}
            %h4.control-sidebar-subheading
              Laravel Integration
              %span.label.label-warning.pull-right 50%
            .progress.progress-xxs
              .progress-bar.progress-bar-warning{:style => "width: 50%"}
        %li
          %a{:href => "javascript:void(0)"}
            %h4.control-sidebar-subheading
              Back End Framework
              %span.label.label-primary.pull-right 68%
            .progress.progress-xxs
              .progress-bar.progress-bar-primary{:style => "width: 68%"}
      / /.control-sidebar-menu
    / /.tab-pane
    / Stats tab content
    #control-sidebar-stats-tab.tab-pane Stats Tab Content
    / /.tab-pane
    / Settings tab content
    #control-sidebar-settings-tab.tab-pane
      %form{:method => "post"}
        %h3.control-sidebar-heading General Settings
        .form-group
          %label.control-sidebar-subheading
            Report panel usage
            %input.pull-right{:checked => "checked", :type => "checkbox"}/
          %p
            Some information about this general settings option
        / /.form-group
        .form-group
          %label.control-sidebar-subheading
            Allow mail redirect
            %input.pull-right{:checked => "checked", :type => "checkbox"}/
          %p
            Other sets of options are available
        / /.form-group
        .form-group
          %label.control-sidebar-subheading
            Expose author name in posts
            %input.pull-right{:checked => "checked", :type => "checkbox"}/
          %p
            Allow the user to show his name in blog posts
        / /.form-group
        %h3.control-sidebar-heading Chat Settings
        .form-group
          %label.control-sidebar-subheading
            Show me as online
            %input.pull-right{:checked => "checked", :type => "checkbox"}/
        / /.form-group
        .form-group
          %label.control-sidebar-subheading
            Turn off notifications
            %input.pull-right{:type => "checkbox"}/
        / /.form-group
        .form-group
          %label.control-sidebar-subheading
            Delete chat history
            %a.text-red.pull-right{:href => "javascript:void(0)"}
              %i.fa.fa-trash-o
        / /.form-group
    / /.tab-pane
/ /.control-sidebar
/
  Add the sidebar's background. This div must be placed
  immediately after the control sidebar
.control-sidebar-bg

app/views/layouts/partials/_footer.html.haml
%footer.main-footer
  .container
    .pull-right.hidden-xs
      %b Version
      0.0.1
    %strong
      Copyright © 2017
      = succeed "." do
        %a{:href => "https://coinstarter.beslan"} Coinstarter
    All rights
    reserved.

app/views/layouts/partials/_header.html.haml
%header.main-header
  %nav.navbar.navbar-static-top
    .container
      .navbar-header
        %a.navbar-brand{:href => "/"}
          %b> Coin
          Starter
        %button.navbar-toggle.collapsed{"data-target" => "#navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %i.fa.fa-bars
      / Collect the nav links, forms, and other content for toggling
      #navbar-collapse.collapse.navbar-collapse.pull-left
        %ul.nav.navbar-nav
          %li.active
            %a{:href => "/"}
              Projects
              %span.sr-only (current)
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Categories
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              - Category.order('name ASC').each do |cat|
                %li
                  = link_to cat.name, projects_path(category: cat.id)
        %form.navbar-form.navbar-left{:role => "search"}
          .form-group
            %input#navbar-search-input.form-control{:placeholder => "Search", :type => "text"}/
      / /.navbar-collapse
      / Navbar Right Menu
      .navbar-custom-menu
        %ul.nav.navbar-nav
          / / Messages: style can be found in dropdown.less
          / %li.dropdown.messages-menu
          /   / Menu toggle button
          /   %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          /     %i.fa.fa-envelope-o
          /     %span.label.label-success 4
          /   %ul.dropdown-menu
          /     %li.header You have 4 messages
          /     %li
          /       / inner menu: contains the messages
          /       %ul.menu
          /         %li
          /           / start message
          /           %a{:href => "#"}
          /             .pull-left
          /               / User Image
          /               %img.img-circle{:alt => "User Image", :src => "../../dist/img/user2-160x160.jpg"}/
          /             / Message title and timestamp
          /             %h4
          /               Support Team
          /               %small
          /                 %i.fa.fa-clock-o
          /                 5 mins
          /             / The message
          /             %p Why not buy a new awesome theme?
          /         / end message
          /       / /.menu
          /     %li.footer
          /       %a{:href => "#"} See All Messages
          / / /.messages-menu
          / / Notifications Menu
          / %li.dropdown.notifications-menu
          /   / Menu toggle button
          /   %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          /     %i.fa.fa-bell-o
          /     %span.label.label-warning 10
          /   %ul.dropdown-menu
          /     %li.header You have 10 notifications
          /     %li
          /       / Inner Menu: contains the notifications
          /       %ul.menu
          /         %li
          /           / start notification
          /           %a{:href => "#"}
          /             %i.fa.fa-users.text-aqua
          /             5 new members joined today
          /         / end notification
          /     %li.footer
          /       %a{:href => "#"} View all
          / / Tasks Menu
          / %li.dropdown.tasks-menu
          /   / Menu Toggle Button
          /   %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
          /     %i.fa.fa-flag-o
          /     %span.label.label-danger 9
          /   %ul.dropdown-menu
          /     %li.header You have 9 tasks
          /     %li
          /       / Inner menu: contains the tasks
          /       %ul.menu
          /         %li
          /           / Task item
          /           %a{:href => "#"}
          /             / Task title and progress text
          /             %h3
          /               Design some buttons
          /               %small.pull-right 20%
          /             / The progress bar
          /             .progress.xs
          /               / Change the css width attribute to simulate progress
          /               .progress-bar.progress-bar-aqua{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "20", :role => "progressbar", :style => "width: 20%"}
          /                 %span.sr-only 20% Complete
          /         / end task item
          /     %li.footer
          /       %a{:href => "#"} View all tasks
          / User Account Menu
          - if current_user
            %li.dropdown.user.user-menu
              / Menu Toggle Button
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %span.hidden-xs= current_user.name
              %ul.dropdown-menu
                / The user image in the menu
                %li.user-header
                  %p
                    = current_user.name
                    %small= "Member since #{current_user.created_at.strftime('%b. %Y')}"
                / Menu Body
                - if current_user && current_user.ethereum_wallet.nil?
                  %li.user-body
                    .row
                      .col-xs-12.text-center
                        %button.btn.btn-primary.btn-block{"data-target" => "#modal-create-wallet", "data-toggle" => "modal"} Create Eth wallet
                /     .col-xs-4.text-center
                /       %a{:href => "#"} Sales
                /     .col-xs-4.text-center
                /       %a{:href => "#"} Friends
                /   / /.row
                / Menu Footer
                %li.user-footer
                  .pull-left
                    =link_to 'Profile', profile_path, method: :get, class: 'btn btn-default btn-flat'
                  .pull-right
                    =link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat'
          - else
            %li
              = link_to 'Registration', new_user_registration_path
            %li
              = link_to 'Login', new_user_session_path

app/views/layouts/partials/_modals.html.haml
- if flash[:alert]
  #modal-alert.modal.modal-danger.fade
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4.modal-title Error
        .modal-body
          %p= flash[:alert]
        .modal-footer
          %button.btn.btn-outline{"data-dismiss" => "modal", :type => "button"} Close
  :javascript
    $(document).ready(function() {
        $('#modal-alert').modal('show');
    } );
- if flash[:notice]
  #modal-notice.modal.modal-primary.fade
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4.modal-title Info
        .modal-body
          %p= flash[:notice]
        .modal-footer
          %button.btn.btn-outline{"data-dismiss" => "modal", :type => "button"} Close
  :javascript
    $(document).ready(function() {
        $('#modal-notice').modal('show');
    } );

#modal-create-wallet.modal.modal-default.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4.modal-title= "Create Ethereum wallet"
      .modal-body
        = form_for(EthereumWallet.new, url: wallets_path, html: {class: 'form-horizontal'}, remote: true) do |f|
          %p= f.password_field :password, class: 'form-control', placeholder: 'Ethereum wallet key password'
          .modal-footer
            = f.submit "Create wallet", class: 'btn btn-info pull-right'
    / /.modal-content
  / /.modal-dialog

app/views/pages/index.html.haml
.container
  .content-wrapper
    / Content Header (Page header)
    %section.content-header
      %h1
        Main page
        %small Projects timeline
      %ol.breadcrumb
        %li
          %i.fa.fa-dashboard
          Home
    / Main content
    %section.content
      / row
      .row
        .col-md-12
          / The time line
          %ul.timeline
            - @projects_by_date.keys.each do |date|
              / timeline time label
              %li.time-label
                %span{class: Project.day_color(date)}
                  = date
              / /.timeline-label
              / timeline item
              - @projects_by_date[date].each do |project|
                %li
                  %i{class: project.category.style}
                  .timeline-item
                    %span.time
                      %i.fa.fa-clock-o
                      = project.created_at.strftime('%H:%M')
                    %h3.timeline-header
                      = link_to project.name, project_path(project.id)
                    .timeline-body
                      = project.description
                      %p
                      .progress
                        .progress-bar.progress-bar-primary.progress-bar-striped{"aria-valuemax" => project.goal, "aria-valuemin" => "0", "aria-valuenow" => project.pledged, :role => "progressbar", :style => "width: #{(project.pledged.to_f/project.goal*100).to_i}%"}
                    .timeline-footer
                      = link_to 'Read more', project_path(project.id), class: 'btn btn-primary btn-xs'
            %li
              %i.fa.fa-clock-o.bg-gray

app/views/projects/_form.html.haml
= form_for(@project, url: projects_path, html: {class: 'form-horizontal'}, method: :post) do |f|
  .box-body
    .form-group
      = f.label :name, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Project name'
    .form-group
      = f.label :description, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_area :description, class: 'form-control', placeholder: 'Project description'
    .form-group
      = f.label :goal, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :goal, class: 'form-control', placeholder: 'Goal'
    .form-group
      = f.label :category, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.select :category_id, Category.all.collect{|p|[p.name, p.id]}, {include_blank: false}, {class: 'form-control'}
    .form-group
      = f.label :due_date, class: 'col-sm-2 control-label'
      .col-sm-10
        .input-group.date
          .input-group-addon
            %i.fa.fa-calendar
          = f.text_field :due_date, class: 'form-control', data:{ provide:'datepicker', "date-format" => "dd/mm/yyyy" }
    
  .box-footer
    = link_to 'Cancel', root_path, class: 'btn btn-default'
    = f.submit "Create", class: 'btn btn-info pull-right'

app/views/projects/index.html.haml
.container
  .content-wrapper
    / Content Header (Page header)
    %section.content-header
      %h1
        Projects
        %small= "in #{@category.name} category"
      %ol.breadcrumb
        %li
          %i.fa.fa-dashboard
          = link_to 'Projects', root_path
        %li
          = @category.name
    / Main content
    %section.content
      / row
      .row
        .col-md-12
          / The time line
          %ul.timeline
            - @projects_by_date.keys.each do |date|
              / timeline time label
              %li.time-label
                %span{class: Project.day_color(date)}
                  = date
              / /.timeline-label
              / timeline item
              - @projects_by_date[date].each do |project|
                %li
                  %i{class: project.category.style}
                  .timeline-item
                    %span.time
                      %i.fa.fa-clock-o
                      = project.created_at.strftime('%H:%M')
                    %h3.timeline-header
                      = link_to project.name, project_path(project.id)
                    .timeline-body
                      = project.description
                      %p
                      .progress
                        .progress-bar.progress-bar-primary.progress-bar-striped{"aria-valuemax" => project.goal, "aria-valuemin" => "0", "aria-valuenow" => project.pledged, :role => "progressbar", :style => "width: #{(project.pledged.to_f/project.goal*100).to_i}%"}
                    .timeline-footer
                      = link_to 'Read more', project_path(project.id), class: 'btn btn-primary btn-xs'
            %li
              %i.fa.fa-clock-o.bg-gray

app/views/projects/new.html.haml
.container
  %section.content-header
    %h1
      New Project
    %ol.breadcrumb
      %li
        %a{:href => "/"}
          %i.fa.fa-dashboard
          Projects
      %li.active New project
  / Main content
  %section.content
    .box.box-info
      .box-header.with-border
        %h3.box-title 
      / /.box-header
      / form start
      = render partial: 'projects/form'

app/views/projects/show.html.haml
.container
  .content-wrapper
    %section.content-header
    %h1
      = @project.name
    %ol.breadcrumb
      %li
        %a{:href => "/"}
          %i
          Projects
      %li
        = link_to projects_path(category: @project.category_id) do
          %i
          = @project.category.name
      %li.active= @project.name

    .box.box-primary
      .box-body.box-profile
        #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
          %ol.carousel-indicators
            %li{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
            %li.active{"data-slide-to" => "1", "data-target" => "#carousel-example-generic"}
            %li{"data-slide-to" => "2", "data-target" => "#carousel-example-generic"}
          .carousel-inner
            .item
              %img{:alt => "First slide", :src => "http://placehold.it/1120x500/39CCCC/ffffff&text=Coinstarter"}/
              .carousel-caption
                First Slide
            .item.active
              %img{:alt => "Second slide", :src => "http://placehold.it/1120x500/3c8dbc/ffffff&text=Coinstarter"}/
              .carousel-caption
                Second Slide
            .item
              %img{:alt => "Third slide", :src => "http://placehold.it/1120x500/f39c12/ffffff&text=Coinstarter"}/
              .carousel-caption
                Third Slide
          %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic"}
            %span.fa.fa-angle-left
          %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic"}
            %span.fa.fa-angle-right
        %h3.profile-username.text-center= @project.name
        %ul.list-group.list-group-unbordered
          %li.list-group-item
            %b Goal
            %a.pull-right= @project.goal
          %li.list-group-item
            %b Pledged
            %a.pull-right= @project.pledged
          %li.list-group-item
            %b Backers
            %a.pull-right= @project.backers_count
          %li.list-group-item
            %b Progress
            .progress
              .progress-bar.progress-bar-primary.progress-bar-striped{"aria-valuemax" => @project.goal, "aria-valuemin" => "0", "aria-valuenow" => @project.pledged, :role => "progressbar", :style => "width: #{(@project.pledged.to_f/@project.goal*100).to_i}%"}
          - if current_user && current_user.ethereum_wallet
            %li.list-group-item
              %button.btn.btn-primary.btn-block{"data-target" => "#modal-back", "data-toggle" => "modal", :type => "button"}
                %b Back this project
          %li.list-group-item
            %p.text-muted= @project.description

    #modal-back.modal.modal-default.fade
      .modal-dialog
        .modal-content
          .modal-header
            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"} ×
            %h4.modal-title= "Back #{@project.name}"
          .modal-body
            = form_for(Transaction.new, url: back_project_path(@project.id), html: {class: 'form-horizontal'}) do |f|
              %p= f.text_field :value, class: 'form-control', placeholder: 'Number in Ether'
              %p= f.password_field :password, class: 'form-control', placeholder: 'Ethereum wallet key password'
              .modal-footer
                = f.submit "Send Ether", class: 'btn btn-info pull-right'
        / /.modal-content
      / /.modal-dialog

app/views/wallets/create.js.erb
<% if @message%>
  alert("<%= @message %>");
<% end %>
<% if @redirect %>
  window.location.href = '/profile';
<% end %>
<% if @close %>
  $('#modal-create-wallet').modal('hide');
  $('.user-body').hide();
<% end %>